Replace and fix deprecated functions
poissonconsulting/poisdata pull request #25
Opened 2023-12-13 18:45 UTC by ColtonRAStephens

Updated code or replaced functions to remove deprecated functions from being used.

2023-12-15 18:15 UTC, aylapear requested changes
Things are looking great, its really nice all the test warnings are gone now

2023-12-15 18:15 UTC, aylapear commented on R/group.R
> +    vld_numeric(x)
I think we can simplify this. Check this set of code out and see what conclusions you draw from the passes and failures. 

```
library(chk)

x <- c(1, 2, 3, NA)
chkor(
  check_values(x, c(1, NA)),
  check_values(x, c(1L, NA))
)

x <- c(1L, 2L, 3L, NA)
chkor(
  check_values(x, c(1, NA)),
  check_values(x, c(1L, NA))
)

x <- c(1, 2, 3, NA)
check_values(x, c(1, NA))
check_values(x, c(1L, NA))

x <- c(1L, 2L, 3L, NA)
check_values(x, c(1, NA))
check_values(x, c(1L, NA))

x <- c(1, 2, 3, NA)
vld_integer(x)
vld_numeric(x)

x <- c(1L, 2L, 3L, NA)
vld_integer(x)
vld_numeric(x)

x <- c(1, 2, 3, NA)
chk_numeric(x)

x <- c(1L, 2L, 3L, NA)
chk_numeric(x)
```

Based on what I read of the function I think the `chk_numeric()` will satisfy what is needed here. It would be worth chatting through together once you go through this.

2023-12-15 18:20 UTC, aylapear commented
Please add yourself to the DESCRIPTION file as a contributor (`role = "ctb"`)

2023-12-15 18:20 UTC, aylapear commented
In the DESCRIPTION file update the minimum version of R to be 4.0.0

2024-01-03 00:01 UTC, ColtonRAStephens commented on R/group.R
> +    vld_numeric(x)
changed!

2024-01-09 20:25 UTC, aylapear approved these changes
Looks great. Please merge the pull request and then delete all the branches related these tasks.

2024-01-09 20:51 UTC, merged